#!/usr/bin/env python3
"""RF2 UI fonts as UZDoom font folders (one PNG per glyph, named by hex code point).

Source: Inter (SIL Open Font License 1.1), read from the local Blender install. Only rasterized
glyph bitmaps ship with the game, no font file; being a Modified Version under the OFL, they ship
with its notice (src/licenses/Inter-OFL.txt). Glyphs are white with anti-aliased alpha so
the engine colour ranges tint them; they are rendered at SCALE times the logical size and the
font.inf "Scale" key brings them back, which keeps them sharp at 1080p/1440p/4K.

Fonts:
  RFText  - Inter Medium, labels, objectives, prompts, menu text
  RFTitle - Inter SemiBold, letter-spaced, level title and menu titles
  RFMenu  - Inter SemiBold at menu size (menus live in a 320x200 virtual space)
  RFHud   - Inter Bold with tabular digits (all digits share one advance) for counters

RF2-UI-01 (27/09) adds two faces, built alone with --ui so the four accepted ones are not rewritten:
  RFLogo  - Inter ExtraBold, large and letter-spaced, capitals only: the game title on the menus
  RFMono  - DejaVu Sans Mono (Bitstream Vera licence), small file-card labels and key hints

Usage: python scripts/mapkit/fonts.py        (writes src/fonts/rftext, rftitle, rfmenu, rfhud)
       python scripts/mapkit/fonts.py --ui   (writes src/fonts/rflogo, rfmono only)
"""
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
INTER = Path(r'C:/Program Files/Blender Foundation/Blender 5.2/5.2/datafiles/fonts/Inter.woff2')
DEJAVU_MONO = Path(r'C:/Program Files/Blender Foundation/Blender 5.2/5.2/datafiles/fonts/DejaVuSansMono.woff2')
SCALE = 4
CHARS = ''.join(chr(c) for c in range(0x21, 0x7F)) + 'ÀÂÄÇÈÉÊËÎÏÔÖÙÛÜŸàâäçèéêëîïôöùûüÿŒœ«»°’–—…'
LOGO_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-.’\'ÀÂÇÈÉÊÎÔÙÛ'
MONO_CHARS = CHARS + '↑↓←→·'


def load(weight, size, path=None):
    font = ImageFont.truetype(str(path or INTER), size)
    if path is None:
        font.set_variation_by_axes([14 if size < 60 else 32, weight])   # optical size, weight
    return font


def build(name, weight, logical_px, tracking=0.0, tabular=False, stroke=3, path=None, chars=CHARS):
    """Glyphs: white core with a thin dark outline. The outline gives the engine a luminosity range
    (a font of one flat white maps to the dark end of every colour range) and keeps the text
    readable on pale plaster. font.inf metrics are logical units (after Scale); glyph pixels are
    SCALE times larger."""
    size = logical_px * SCALE
    font = load(weight, size, path)
    ascent, descent = font.getmetrics()
    height = ascent + descent + 2 * stroke
    out = ROOT / 'src' / 'fonts' / name.lower()
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob('*.png'):
        old.unlink()
    digit_adv = max(font.getlength(d) for d in '0123456789')
    pad = round(tracking * size)
    for ch in chars:
        adv = font.getlength(ch)
        if tabular and ch.isdigit():
            adv = digit_adv
        w = max(1, round(adv) + pad + 2 * stroke)
        img = Image.new('RGBA', (w, height), (255, 255, 255, 0))
        d = ImageDraw.Draw(img)
        x = (w - font.getlength(ch)) / 2 if (tabular and ch.isdigit()) else stroke + pad / 2
        d.text((x, stroke), ch, font=font, fill=(255, 255, 255, 255), stroke_width=stroke, stroke_fill=(18, 16, 16, 215))
        img.save(out / f'{ord(ch):04X}.png', optimize=True)
    space = round((font.getlength(' ') + pad) / SCALE)
    source = 'DejaVu Sans Mono (Bitstream Vera licence)' if path == DEJAVU_MONO else f'Inter (OFL 1.1), weight {weight}'
    lines = [f'// Generated by scripts/mapkit/fonts.py from {source}.',
             f'Scale {SCALE}', f'FontHeight {round(height / SCALE)}', f'SpaceWidth {space}',
             f'Kerning {-(2 * stroke // SCALE)}']
    (out / 'font.inf').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    return out, height


def main():
    if '--ui' in sys.argv:
        jobs = ((('RFLogo', 800, 40, 0.10), dict(stroke=6, chars=LOGO_CHARS)),
                (('RFMono', 400, 12, 0.02), dict(path=DEJAVU_MONO, chars=MONO_CHARS)))
    else:
        jobs = tuple((a, {}) for a in (('RFText', 500, 12), ('RFTitle', 600, 18, 0.06), ('RFMenu', 600, 12, 0.04), ('RFHud', 700, 16, 0.0, True)))
    for args, kw in jobs:
        out, h = build(*args, **kw)
        print(f'{args[0]}: {len(list(out.glob("*.png")))} glyphs, height {h}px -> {out}')


if __name__ == '__main__':
    main()
