#!/usr/bin/env python3
"""World (pickup) models of RF01: FN FAL and Browning Hi-Power lying on their side, FAL magazine,
9 mm carton, field dressing, grille key and service passe.

Low-poly OBJ meshes built from boxes, tapered blocks and octagonal prisms in design centimetres
(Y up, X along the barrel), with flat normals and UVs into a small palette texture. They replace
the flat pickup sprites through MODELDEF (the sprites stay as HUD icons); first-person frames are
untouched. Weapon proportions follow the first-person FAL; small items are drawn about 1.6x life
size so they read at pickup distance, like the sprites they replace.

Usage: python scripts/mapkit/weapon_models.py
Output: src/models/weapons/*.obj, weapons_palette.png
"""
import math
from pathlib import Path
from PIL import Image, ImageDraw
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'src' / 'models' / 'weapons'
# palette swatches: (column, row) in a 4x4 grid of 16 px cells
PALETTE = {
    'metal': ((42, 42, 45), (0, 0)),
    'metal_edge': ((78, 78, 82), (1, 0)),
    'polymer': ((34, 33, 32), (2, 0)),
    'bore': ((12, 12, 12), (3, 0)),
    'butt': ((24, 24, 24), (0, 1)),
    'grip': ((52, 44, 38), (1, 1)),
    'card': ((150, 122, 82), (2, 1)),
    'card_dark': ((104, 84, 56), (3, 1)),
    'khaki': ((128, 118, 86), (0, 2)),
    'red': ((150, 36, 36), (1, 2)),
    'iron': ((88, 86, 82), (2, 2)),
    'brass': ((168, 138, 70), (3, 2)),
    'leather': ((96, 58, 36), (0, 3)),
    'paper': ((214, 206, 180), (1, 3)),
}


class Mesh:
    def __init__(self, name):
        self.name = name
        self.v, self.vt, self.vn, self.f = [], [], [], []
        self.uv = {}

    def _uv(self, mat):
        if mat not in self.uv:
            col, row = PALETTE[mat][1]
            self.vt.append(((col + 0.5) / 4, 1 - (row + 0.5) / 4))
            self.uv[mat] = len(self.vt)
        return self.uv[mat]

    def tri(self, a, b, c, mat):
        n = np.cross(np.subtract(b, a), np.subtract(c, a))
        L = np.linalg.norm(n)
        if L < 1e-9:
            return
        self.vn.append(tuple(n / L))
        ni, ti = len(self.vn), self._uv(mat)
        idx = []
        for p in (a, b, c):
            self.v.append(tuple(p))
            idx.append(len(self.v))
        self.f.append(tuple((i, ti, ni) for i in idx))

    def quad(self, a, b, c, d, mat):
        self.tri(a, b, c, mat)
        self.tri(a, c, d, mat)

    def hexa(self, corners, mat):
        """8 corners: bottom face (x0z0, x1z0, x1z1, x0z1) then top face in the same order."""
        b0, b1, b2, b3, t0, t1, t2, t3 = corners
        self.quad(b0, b3, b2, b1, mat)   # bottom
        self.quad(t0, t1, t2, t3, mat)   # top
        self.quad(b0, b1, t1, t0, mat)
        self.quad(b1, b2, t2, t1, mat)
        self.quad(b2, b3, t3, t2, mat)
        self.quad(b3, b0, t0, t3, mat)

    def box(self, x0, x1, y0, y1, z0, z1, mat, shear=0.0):
        """Axis box; shear moves the bottom face along X by shear * height (raked grips)."""
        s = shear * (y1 - y0)
        self.hexa([(x0 + s, y0, z0), (x1 + s, y0, z0), (x1 + s, y0, z1), (x0 + s, y0, z1),
                   (x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)], mat)

    def taper(self, xa, xb, ya0, ya1, yb0, yb1, zw, mat):
        """Block from x=xa (height ya0..ya1) to x=xb (height yb0..yb1), half width zw."""
        self.hexa([(xa, ya0, -zw), (xb, yb0, -zw), (xb, yb0, zw), (xa, ya0, zw),
                   (xa, ya1, -zw), (xb, yb1, -zw), (xb, yb1, zw), (xa, ya1, zw)], mat)

    def tube(self, x0, x1, yc, r, mat, sides=8, cap='metal'):
        ring = [(math.cos(2 * math.pi * k / sides) * r, math.sin(2 * math.pi * k / sides) * r) for k in range(sides)]
        for k in range(sides):
            (ya, za), (yb, zb) = ring[k], ring[(k + 1) % sides]
            self.quad((x0, yc + ya, za), (x0, yc + yb, zb), (x1, yc + yb, zb), (x1, yc + ya, za), mat)
        for k in range(1, sides - 1):   # caps
            self.tri((x1, yc + ring[0][0], ring[0][1]), (x1, yc + ring[k][0], ring[k][1]), (x1, yc + ring[k + 1][0], ring[k + 1][1]), cap)
            self.tri((x0, yc + ring[0][0], ring[0][1]), (x0, yc + ring[k + 1][0], ring[k + 1][1]), (x0, yc + ring[k][0], ring[k][1]), cap)

    def lay_on_side(self):
        """Roll 90 degrees about X so the weapon rests on its left flank, then sit it on y=0."""
        self.v = [(x, z, -y) for (x, y, z) in self.v]
        self.vn = [(x, z, -y) for (x, y, z) in self.vn]
        low = min(p[1] for p in self.v)
        self.v = [(x, y - low, z) for (x, y, z) in self.v]

    def write(self, path):
        lines = [f'# RF2 {self.name}: generated by scripts/mapkit/weapon_models.py. Centimetres, Y up.',
                 f'o {self.name}', 'usemtl weapons_palette.png']
        lines += [f'v {x:.4f} {y:.4f} {z:.4f}' for (x, y, z) in self.v]
        lines += [f'vt {u:.4f} {t:.4f}' for (u, t) in self.vt]
        lines += [f'vn {x:.4f} {y:.4f} {z:.4f}' for (x, y, z) in self.vn]
        lines += ['f ' + ' '.join(f'{a}/{b}/{c}' for (a, b, c) in face) for face in self.f]
        path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def fal():
    m = Mesh('fal_world')
    m.box(-10, 18, 0, 6.5, -2.1, 2.1, 'metal')                 # receiver
    m.box(0, 10, 7.2, 8.0, -0.6, 0.6, 'metal')                 # carrying handle
    m.box(0, 1, 6.5, 7.2, -0.6, 0.6, 'metal')
    m.box(9, 10, 6.5, 7.2, -0.6, 0.6, 'metal')
    m.box(-9, -7, 6.5, 8.6, -0.6, 0.6, 'metal_edge')           # rear sight
    m.box(12, 14, 4.0, 5.2, 2.1, 5.0, 'metal_edge')            # charging handle (left)
    m.box(18, 40, 0.8, 6.2, -2.4, 2.4, 'polymer')              # handguard
    for x in range(21, 38, 3):                                 # handguard vents
        m.box(x, x + 1.2, 3.0, 5.4, 2.4, 2.5, 'bore')
    m.tube(40, 60, 4.2, 0.9, 'metal')                          # barrel
    m.box(52, 55, 4.2, 9.5, -0.6, 0.6, 'metal')                # front sight
    m.tube(60, 66, 4.2, 1.25, 'metal_edge', cap='bore')        # flash hider
    m.box(5, 12, -16, 0, -1.6, 1.6, 'metal', shear=0.25)       # 20-round magazine, raked forward
    m.box(-12, -6, -11, 0, -1.8, 1.8, 'grip', shear=-0.35)     # pistol grip, raked back
    m.box(-4, 4, -4.0, -3.2, -0.5, 0.5, 'metal')               # trigger guard
    m.box(3.2, 4, -4.0, 0, -0.5, 0.5, 'metal')
    m.taper(-10, -48, 0.5, 5.5, -9.0, 6.0, 2.0, 'polymer')     # stock
    m.box(-49, -48, -9.0, 6.0, -2.1, 2.1, 'butt')              # butt plate
    m.lay_on_side()
    return m


def browning():
    m = Mesh('browning_world')
    m.box(-10, 10, 3.0, 6.2, -1.4, 1.4, 'metal')               # slide
    for x in range(-9, -4):                                    # rear serrations
        m.box(x, x + 0.5, 3.4, 6.0, 1.4, 1.5, 'bore')
    m.box(-10, 8, 0.0, 3.0, -1.3, 1.3, 'metal_edge')           # frame
    m.tube(10, 10.6, 4.6, 0.6, 'metal', cap='bore')            # muzzle
    m.box(-9, -3, -11, 0, -1.6, 1.6, 'grip', shear=-0.3)       # grip panels
    m.box(-4, 3, -2.8, -2.2, -0.45, 0.45, 'metal')             # trigger guard
    m.box(2.4, 3, -2.8, 0, -0.45, 0.45, 'metal')
    m.box(-11.2, -10, 5.0, 6.6, -0.5, 0.5, 'metal')            # hammer
    m.lay_on_side()
    return m


def rifle_magazine():
    """20-round FAL magazine lying flat, readable at pickup scale (about 1.6x life size)."""
    m = Mesh('mag_world')
    m.box(-15, 15, 0, 3.6, -5, 5, 'metal')                       # body
    for x in range(-12, 13, 6):                                  # stiffening ribs
        m.box(x, x + 1.2, 3.6, 4.0, -4.2, 4.2, 'metal_edge')
    m.box(15, 17, 0, 3.2, -5.2, 5.2, 'metal_edge')               # floor plate
    m.box(-17, -15, 0.6, 3.0, -3.0, 3.0, 'brass')                # top round in the feed lips
    return m


def pistol_box():
    """Carton of 9 mm cartridges, lid ajar, one round lying beside it."""
    m = Mesh('box9_world')
    m.box(-10, 10, 0, 7, -7, 7, 'card')
    m.box(-10.4, 10.4, 7, 8, -7.4, 7.4, 'card_dark')             # lid
    m.box(-4, 4, 7.9, 8.1, -4, 4, 'paper')                       # blank label
    m.tube(12, 16, 1.0, 1.0, 'brass', cap='brass')               # loose round
    return m


def dressing():
    """Field dressing: khaki wrapped packet with a red cross band."""
    m = Mesh('dressing_world')
    m.box(-12, 12, 0, 5, -8, 8, 'khaki')
    m.box(-2.5, 2.5, 5, 5.3, -8, 8, 'red')                        # cross bands at two heights:
    m.box(-12, 12, 5, 5.2, -2.5, 2.5, 'red')                       # no coplanar faces (z-fighting)
    return m


def key(name, tag):
    """Heavy iron key with a ring; tag 'brass' (grille) or 'leather' (passe) hangs from it."""
    m = Mesh(name)
    for k in range(8):                                           # ring as eight short bars
        a0, a1 = 2 * math.pi * k / 8, 2 * math.pi * (k + 1) / 8
        cx0, cz0 = -14 + math.cos(a0) * 4, math.sin(a0) * 4
        cx1, cz1 = -14 + math.cos(a1) * 4, math.sin(a1) * 4
        m.box(min(cx0, cx1) - 0.6, max(cx0, cx1) + 0.6, 0, 1.2, min(cz0, cz1) - 0.6, max(cz0, cz1) + 0.6, 'iron')
    m.box(-10, 8, 0, 1.4, -0.8, 0.8, 'iron')                     # shaft
    m.box(4, 8, 0, 1.4, 0.8, 4.0, 'iron')                        # bit
    m.box(-24, -18, 0, 0.8, -4, 4, tag)                          # tag
    return m


def palette(path):
    img = Image.new('RGB', (64, 64), (0, 0, 0))
    d = ImageDraw.Draw(img)
    for rgb, (c, r) in PALETTE.values():
        d.rectangle([c * 16, r * 16, c * 16 + 15, r * 16 + 15], fill=rgb)
    img.save(path)


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for mesh in (fal(), browning(), rifle_magazine(), pistol_box(), dressing(), key('key_grille_world', 'brass'),
                 key('key_passe_world', 'leather')):
        mesh.write(OUT / f'{mesh.name}.obj')
        xs = [p[0] for p in mesh.v]
        print(f'{mesh.name}: {len(mesh.f)} triangles, length {max(xs) - min(xs):.0f} cm')
    palette(OUT / 'weapons_palette.png')


if __name__ == '__main__':
    main()
